### ISSUE TITLE
Could we also havea non-toggle commands?

### ISSUE THREAD

**Issue by Millani** [KabbAmine/vullScreen.vim#3]
It would be grate if we could also have two other simple commands: one to enter and one to exit full-screen. That is, two separate commands that do not toggle the full-screen mode. The reason they are needed is the following. If you have Vim already maximized, exit Vim to the the terminal and then open Vim again, the plugin makes the terminal screen get de-maximized, or in other words, restored to non-maximized state.

Obviously, it's hard to believe that this was the original intention of the plugin, so perhaps it is a bug.

**Comment by KabbAmine** [comment]
Its easily doable by using `add`/`remove` instead of `toggle` in the `wmctrl`'s command.
You may push a PR if you want or wait for mine in the following days.

> Obviously, it's hard to believe that this was the original intention of the plugin, so perhaps it is a bug.

It was the original and only intention of the plugin :smile: I've made vullscreen years ago when I was using exclusively gvim and creating a lot of vim plugins (I still do), but now that I'm using vim only in terminals, I do not need the plugin anymore.

**Comment by Millani** [comment]
Haha awesome, thanks! I guess I will have to wait for your update. I am just now learning the vimscript syntax so while I think I already envision what to do, better to not mess it up. Thanks for looking into this!

**Comment by KabbAmine** [comment]
Instead of commands, you can now use the new functions `vullScreen#enable()` and `vullScreen#disable()`.

**Comment by Millani** [comment]
That works easily and smoothly, many thanks!
